baseURL = "https://www.kylinnetzephyrus.ltd"
disableLanguages = ["fr"]
disqusShortname = ""
paginate = "8"
summaryLength = "15"
theme = "meghna-hugo"
title = "Kylinnet"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = "2"
[menu]
static = []
[[menu.main]]
URL = "about"
name = "about"
weight = 1
[[menu.main]]
URL = "services"
name = "services"
weight = 2
[[menu.main]]
URL = "skill"
name = "skill"
weight = "3"
[[menu.main]]
URL = "portfolio"
name = "portfolio"
weight = "4"
[[menu.main]]
URL = "contact"
name = "contact"
weight = 7
[params]
author = "Liusoon"
description = "Responsive Multipurpose Parallax HTML5 Template"
google_analytics_id = "AIzaSyBLfZ02cQCp_o5VM-2Q5bGAdDmY5d889mY"
logo = "static/images/logo.png"
post_share = true
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyAtJkYe0El_XHj02RamZOjoRj6YDc2FdAo"
map_latitude = " 30.652248  "
map_longitude = "104.069778"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = ""
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = ""
[[params.plugins.js]]
link = ""
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[params.preloader]
enable = true
preloader = "/images/logo-2.png"
[[params.social]]
icon = "ti-facebook"
link = "#"
[[params.social]]
icon = "ti-twitter-alt"
link = "https://twitter.com/SllnL"
[[params.social]]
icon = "ti-youtube"
link = "#"
[[params.social]]
icon = "ti-email"
link = "#"
[[params.social]]
icon = "ti-dribbble"
link = "#"
