baseURL = "https://www.kylinnetzephyrus.ltd"
disableLanguages = ["fr"]
disqusShortname = ""
paginate = "6"
summaryLength = "15"
theme = "meghna-hugo"
title = ""
[Languages.en]
contentDir = "content/english"
copyright = ""
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = "2"
[menu]
static = []
[menu.main]
URL = "portfolio"
name = "portfolio"
weight = 4
[params]
author = "Themefisher"
description = "Responsive Multipurpose Parallax HTML5 Template"
google_analytics_id = "AIzaSyBLfZ02cQCp_o5VM-2Q5bGAdDmY5d889mY"
logo = "/images/logo.png"
post_share = true
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyAtJkYe0El_XHj02RamZOjoRj6YDc2FdAo"
map_latitude = " 30.652248  "
map_longitude = "104.069778"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = false
preloader = "/images/logo.png"
[[params.social]]
icon = "ti-facebook"
link = "#"
[[params.social]]
icon = "ti-twitter-alt"
link = "https://twitter.com/SllnL"
[[params.social]]
icon = "ti-youtube"
link = "#"
[[params.social]]
icon = "ti-email"
link = "#"
[[params.social]]
icon = "ti-dribbble"
link = "#"
